### ISSUE TITLE
string.replace is not a function (Node 10.15)

### ISSUE THREAD

**Issue by shiftgeist** [psmyrdek/ng-up#35]
When running:
`ng-up provider --dry`

Error Callback:
```
[...]/node/v10.15.3/lib/node_modules/ng-up/lib/common/stringUtils.js:3
module.exports.camelCaseToKebabCase = string => string.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase()
                                                       ^

TypeError: string.replace is not a function
    at module.exports.camelCaseToKebabCase.string ([...]/node/v10.15.3/lib/node_modules/ng-up/lib/common/stringUtils.js:3:56)
    at prepareData ([...]/node/v10.15.3/lib/node_modules/ng-up/lib/providers/prepareData.js:5:42)
    at module.exports (/home/fhungenberg/.nvm/versions/node/v10.15.3/lib/node_modules/ng-up/lib/providers/command.js:15:5)
    at Object.<anonymous> (/home/fhungenberg/.nvm/versions/node/v10.15.3/lib/node_modules/ng-up/bin/ng-up-provider.js:15:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)

```

**Comment by psmyrdek** [comment]
Thank for pointing it out, will investigate.

**Comment by psmyrdek** [comment]
@shiftgeist It seems that your command lacks the provider name. After executing it like:
`ng-up provider --name i18n --dry`
it works fine. I agree that error handling could be more meaningful, though.
